language: elm
deploy:
    provider: pages
    fqdn: howmuch.coffee
    local-dir: dist/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
after_success:
    - elm make src/Main.elm --output=dist/index.html
